### PR TITLE
test the roots compilation

### PR DESCRIPTION
**Pull request by kylemac**
now tests cover whether the project was able to actually be compiled with roots. this should lay a foundation and catch some edge cases for us

### CODE REVIEW

**Comment by jescalan** [comment]
Looks good, thanks for this set of updates!

**Comment by jescalan** [comment]
Just make sure to PR this into `roots-dev` as well :grinning:

**Comment by kylemac** [comment]
we should discuss which features you think are valuable for the `roots-dev` version. imo, we'll need to strike a balance between power (in the form of config options) and simplicity. 

i was imagining that there will be a fork that'll happen between the `base` project for `roots-dev` and the `base` project i desire for the @carrot/owners team. let's brainstorm a little next time you're free @jenius and come up with a little plan of attack for both projects

**Comment by jescalan** [comment]
Ah good point. Didn't realize you wanted to split these, but it makes sense. For the roots default option, I'd like to offer options, but not force peoples' hands in any particular direction really. But yeah we can discuss this for sure!

**Pull request merged**
