### PR TITLE
Adding .swp files to ignores for vim users

### PR DESCRIPTION
**Pull request by BrandonRomano**

### CODE REVIEW

**Comment by kylemac** [comment]
you'll want to duplicate this in `app.production.coffee` as well, since it applies to both

**Comment by BrandonRomano** [comment]
Whoop, didn't know there was two!

**Comment by BrandonRomano** [comment]
@kylemac did an `--amend` on this one.

Also noticed there were some missing commas in some of the lines... So I added that too.

**Comment by kylemac** [comment]
the lack of commas was an affordance of coffeescript

**Comment by BrandonRomano** [comment]
oh, well some lines had commas and some didn't.

Which do we prefer and I can set them all that way?

**Comment by kylemac** [comment]
i like it w/o

**Comment by BrandonRomano** [comment]
@kylemac did another `--amend`.  Without it is :cat:!

I just couldn't handle multiple styles in the same array :stuck_out_tongue_winking_eye:

**Comment by kylemac** [comment]
:+1:

**Pull request merged**
